version: '3.7'

services:
  #############################################
  # Start http://web:3000/
  #############################################
  web:
    # if not --build and kurs-pm-web already exists in
    # your local computers registry 'image' is used.
    image: $LOCAL_IMAGE_ID

    environment:
      - SERVICE_PUBLISH=/kurs-pm
      - SERVER_PORT=3000
      - SESSION_SECRET=1234
      - SESSION_KEY=kurs-pm-data-web.pid
      - LOGGING_ACCESS_LOG=true
      - LDAP_BASE
      - LDAP_URI
      - LDAP_PASSWORD
      - KURS_PM_DATA_API_URI
      - KURS_PM_DATA_API_KEY
      - KURS_INFO_API_URI
      - KURS_INFO_API_KEY
      - KURSPLAN_API_KEY
      - KURSPLAN_API_URI
      - REDIS_URI
      - CAS_SSO_URI=https://login-r.referens.sys.kth.se
      - APPINSIGHTS_INSTRUMENTATIONKEY

    ports:
      - 3000:3000

  #############################################
  # Start the client running tests
  # agains http://web:3000/
  #############################################
  integration-tests:
    # Build client image and run tests
    # from inside that.
    build: ./test/integration
    depends_on:
      - web
